# This Python script was NOT written by me! This was written by a collaborator of Dr. Oliveira and Masoumeh Mahmoudi
# I have edited their script to be a command line executable with user-input 
# When running this script, it will request two inputs:
# The first is the total number of bands for the specific calculation and the second is the total number of k-points 
# The output of this script is COF_BLTZTRP.tau_k

#!/usr/bin/env python

import numpy as np
import subprocess
from io import StringIO

###constants
ctau = "1.00E-14"
nbnd = int(input('Number of bands: '))
nok = int(input('Number of k-points: '))
################

def run_shell(command):
    subprocess.call([command], shell=True)

def check_shell(command,typ):
    tmp = subprocess.check_output([command], shell=True).strip()
    if typ == "int":
        return int(str(tmp,'utf-8'))
    elif typ == "float":
        return float(str(tmp,'utf-8'))
    else:
        return str(tmp,'utf-8')

basic_params = (f"\nBoltzTraP tau_k file generated by Ransell for T=   300.000000\n      {nok}      1    0  ! nk, nspin, Fermi level(Ry) : lifetimes below in seconds")

kpt = 3

with open("COF_BLZTRP.tau_k", 'w') as file_tmp:
        file_tmp.write(basic_params.strip())
        file_tmp.write("\n")
        for i in range(nok):
        #print(kpt)
            sh_cmd = "sed -n '%s p' COF.energy" %kpt
            k_points = check_shell(sh_cmd, "s")
            kpt += nbnd + 1
            file_tmp.write("%s\n" % k_points )
            for j in range(nbnd):
                file_tmp.write("%s\n" % ctau)